<a href="https://colab.research.google.com/github/ruthetum/Deeplearning-NLP/blob/master/OneHotEncoding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* 기본 세팅

In [0]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import nltk
!pip install konlpy
import konlpy

# 다운로드
nltk.download('punkt')
nltk.download('stopwords')

Instructions for updating:
non-resource variables are not supported in the long term
     |████████████████████████████████| 19.4MB 1.2MB/s 
     |████████████████████████████████| 92kB 7.7MB/s 
     |████████████████████████████████| 2.4MB 44.3MB/s 
  Found existing installation: beautifulsoup4 4.6.3
    Uninstalling beautifulsoup4-4.6.3:
      Successfully uninstalled beautifulsoup4-4.6.3
  Found existing installation: tweepy 3.6.0
    Uninstalling tweepy-3.6.0:
      Successfully uninstalled tweepy-3.6.0
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [0]:
# 토큰화 (형태소)
from konlpy.tag import Okt  
okt=Okt()  
token=okt.morphs("나는 자연어 처리를 배운다")  
print(token)

['나', '는', '자연어', '처리', '를', '배운다']


In [0]:
# 각 단어에 인덱스 부여
word2index={}
for voca in token:
     if voca not in word2index.keys():
       word2index[voca]=len(word2index)
print(word2index)

{'나': 0, '는': 1, '자연어': 2, '처리': 3, '를': 4, '배운다': 5}


In [0]:
# 다 0 으로 바꾸고 원하는 단어만 인덱스 찾아서 1로 바꿔주기
def one_hot_encoding(word, word2index):
       one_hot_vector = [0]*(len(word2index))
       index=word2index[word]
       one_hot_vector[index]=1
       return one_hot_vector

one_hot_encoding("자연어",word2index)

[0, 0, 1, 0, 0, 0]

# 케라스를 이용한 원-핫 인코딩

to_categorical : 케라스에서 원-핫 인코딩할 때 사용

In [0]:
# 빈도 순으로 인덱스 부여 (토크나이저)
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical

text="나랑 점심 먹으러 갈래 점심 메뉴는 햄버거 갈래 갈래 햄버거 최고야"

t = Tokenizer()
t.fit_on_texts([text])
print(t.word_index)

{'갈래': 1, '점심': 2, '햄버거': 3, '나랑': 4, '먹으러': 5, '메뉴는': 6, '최고야': 7}


In [0]:
sub_text="점심 먹으러 갈래 메뉴는 햄버거 최고야"
encoded=t.texts_to_sequences([sub_text])
print(encoded)

[[2, 5, 1, 6, 3, 7]]


In [0]:
one_hot = to_categorical(encoded)
print(one_hot)

[[[0. 0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 1.]]]


# 원-핫 인코딩의 한계

* 단어의 개수가 늘어날수록 벡터를 저장하기 위한 공간이 커짐(벡터의 차원 증가)
* 단어의 유사도를 표현하지 못함

Ex. 호랑이, 고양이, 강아지, 늑대가 있을 경우 각각을 1로 표현하는데
호랑이와 고양이, 강아지와 늑대가 유사한 것을 표현할 수 없음  


### 단점을 해결하기 위해 단어의 잠재 의미를 반영하여 다차원 공간에 벡터화 하는 기법으로 크게 2가지 있음

*   카운트 기반 벡터화 방법 : LSA, HAL
*   예측 기반 벡터화 방법 : NNLM, RNNLM, Word2Vec
*   둘 다 사용하는 방법 : GloVe



